export const footwearProducts = [
  {
    id: "f016cmvno-arctic",
    title: "F016CMVNO, Arctic",
    fullName: "F016CMVNO, Arctic---Semi-aniline / Smooth flower",
    subtitle: "LEATHER SUITABLE FOR FOOTWEAR PRODUCTION",
    thickness: "1.2 / 1.4 mm",
    rawhide: "European",
    src: "/slides/Screenshot_64.png",
    rawMaterial: "We use best bovine and calf skins of European origin.",
    processing: "On our premises we carry out chrome retanning, advanced dyeing, and premium smooth flower finishing tailored for high-end footwear.",
    productDetails: "This leather has a full-bodied, soft feel and is characterized by chrome retanning and advanced finishing techniques, designed to meet the needs of footwear and leather product clients. Additional colours are available, and the retanning, dyeing, and finishing processes can be customized for different product applications.",
    desc: "This leather has a full-bodied, soft feel and is characterized by chrome retanning and advanced finishing techniques, designed to meet the needs of footwear and leather product clients. (Additional colours are available, and the retanning, dyeing, and finishing processes can be customized for different product applications)."
  },
  {
    id: "f015cd-mallow",
    title: "F015CD, Mallow",
    fullName: "F015CD, Mallow---Semi-Aniline/Full grain.",
    subtitle: "LEATHER SUITABLE FOR FOOTWEAR PRODUCTION",
    thickness: "1.0 / 1.2 mm",
    rawhide: "Europe + GB + NZ",
    src: "/slides/Screenshot_1.png",
    rawMaterial: "We use premium rawhides sourced from high-quality farms across Europe, Great Britain, and New Zealand.",
    processing: "On our premises we carry out sanding, chrome retanning, and apply a glossy semi-aniline finish that enhances deep color dimensions.",
    productDetails: "This is a sanded leather, featuring chrome retanning and a semi-aniline glossy finish that enhances colour depth. More colours are available, and the tanning, retanning, dyeing, and finishing processes can be tailored to suit various product applications.",
    desc: "This is a sanded leather, featuring chrome retanning and a semi-aniline glossy finish that enhances colour depth. More colours are available, and the tanning, retanning, dyeing, and finishing processes can be tailored to suit various product applications."
  },
  {
    id: "f015cda-warm-leather",
    title: "F015CDA, Warm Leather",
    fullName: "F015CDA, Warm leather---Semi Aniline/Full grain.",
    subtitle: "LEATHER SUITABLE FOR FOOTWEAR PRODUCTION",
    thickness: "1.3 / 1.5 mm",
    rawhide: "European",
    src: "/slides/Screenshot_2.png",
    rawMaterial: "We use best bovine and calf skins of European origin.",
    processing: "On our premises we carry out specialized chrome retanning and semi-aniline finishing, maintaining a regular, beautiful grain structure.",
    productDetails: "This is a full-grain leather, characterized by chrome retanning and a semi-aniline finish with a regular grain, designed to meet the needs of footwear and leather goods customers. More colours are available and can be customized for different product applications.",
    desc: "This is a full-grain leather, characterized by chrome retanning and a semi-aniline finish with a regular grain, designed to meet the needs of footwear and leather goods customers. More colours are available and can be customized for different product applications."
  },
  {
    id: "f011tmle-sea-blue",
    title: "F011TMLE, Sea Blue",
    fullName: "F011TMLE, Sea blue---Aniline/Fine grain",
    subtitle: "LEATHER SUITABLE FOR FOOTWEAR PRODUCTION",
    thickness: "1.1 / 1.2 mm",
    rawhide: "European",
    src: "/slides/Screenshot_3.png",
    rawMaterial: "We select the finest bovine skins to secure an pristine, high-grade fine grain surface.",
    processing: "On our premises we apply clean aniline drum dyeing and extremely delicate protective finishing to preserve the natural grain look.",
    productDetails: "This top-fine grain aniline provides a smooth, rich appearance that is ideal for luxurious footwear. More colours are available, and it can be modified for different product applications.",
    desc: "This top-fine grain aniline provides a smooth, rich appearance that is ideal for luxurious footwear. More colours are available, and it can be modified for different product applications."
  },
  {
    id: "f016tnp-navy-blue",
    title: "F016TNP, Navy Blue",
    fullName: "F016TNP, Navy blue---Nappa/Full grain.",
    subtitle: "LEATHER SUITABLE FOR FOOTWEAR PRODUCTION",
    thickness: "1.0 / 1.2 mm",
    rawhide: "Europe",
    src: "/slides/Screenshot_4.png",
    rawMaterial: "We use top-tier full-grain bovine skins selected from premier European tanneries.",
    processing: "On our premises we execute advanced Nappa softening retannage to achieve an enveloping structure and silky feel.",
    productDetails: "Nappa Calf is a full-grain bovine leather with a soft and enveloping structure. It has a silky hand feel that is pleasant to the touch. The final look is semi-gloss, with a very soft, transparent, and natural appearance. More colours are available and can be modified for different product uses.",
    desc: "Nappa Calf is a full-grain bovine leather with a soft and enveloping structure. It has a silky hand feel that is pleasant to the touch. The final look is semi-gloss, with a very soft, transparent, and natural appearance. More colours are available and can be modified for different product uses."
  },
  {
    id: "f016cly-leather",
    title: "F016CLY, Leather",
    fullName: "F016CLY, Leather---Semi-Aniline /Smooth full-grain",
    subtitle: "LEATHER SUITABLE FOR FOOTWEAR PRODUCTION",
    thickness: "1.0 / 1.2 mm",
    rawhide: "European",
    src: "/slides/Screenshot_5.png",
    rawMaterial: "We select best-in-class European rawhides to guarantee a smooth and clean full-grain surface.",
    processing: "On our premises we carry out chrome retannage and apply a refined aniline-wax glaze that results in a gorgeous natural handle.",
    productDetails: "This soft-touch leather features chrome retannage and an aniline-wax finish, offering a refined and natural appearance. It is ideal for footwear production. More colours are available, and it is possible to modify the retanning, dyeing, and finishing processes for various product applications.",
    desc: "This soft-touch leather features chrome retannage and an aniline-wax finish, offering a refined and natural appearance. It is ideal for footwear production. More colours are available, and it is possible to modify the retanning, dyeing, and finishing processes for various product applications."
  },
  {
    id: "f09tm-burnt-red",
    title: "F09TM, Burnt Red",
    fullName: "F09TM, Burnt Red---Nappa/Full Grain",
    subtitle: "LEATHER SUITABLE FOR FOOTWEAR PRODUCTION",
    thickness: "1.1 / 1.2 mm",
    rawhide: "Great Britain + Europe",
    src: "/slides/Screenshot_6.png",
    rawMaterial: "We use fine full-grain bovine leather of premium Great Britain and European provenance.",
    processing: "On our premises we utilize our signature aniline dyeing processes that ensure deep, consistent color saturation and incomparable softness.",
    productDetails: "This Nappa collection embodies the true spirit of luxury footwear, crafted from fine full-grain bovine leather of European provenance, known for its incomparable softness and elegant appearance. The aniline finish accentuates the natural beauty of the leather while ensuring depth and consistent colour with a soft hand feel. More colours are available, and the leather can be modified for different product applications.",
    desc: "This Nappa collection embodies the true spirit of luxury footwear, crafted from fine full-grain bovine leather of European provenance, known for its incomparable softness and elegant appearance. The aniline finish accentuates the natural beauty of the leather while ensuring depth and consistent colour with a soft hand feel. More colours are available, and the leather can be modified for different product applications."
  },
  {
    id: "f08cl-midnight",
    title: "F08CL, Midnight",
    fullName: "F08CL, Midnight---Nubuck/Full grain.",
    subtitle: "LEATHER SUITABLE FOR FOOTWEAR PRODUCTION",
    thickness: "1.2 / 1.4 mm",
    rawhide: "Europe + New Zealand",
    src: "/slides/Screenshot_7.png",
    rawMaterial: "We source choice bovine hides from European and New Zealand farms for unmatched density and quality.",
    processing: "On our premises we gently buff the surface and apply our customized velvet finish for that recognizable Nubuck hand feel.",
    productDetails: "The Nubuck collection is designed to satisfy the demands of stylish footwear, featuring a rich, innovative, and sophisticated finish. Crafted from premium European hides, it is lightly buffed to achieve a soft, velvety touch while retaining the natural grain. More colours are available, and customization is possible for various product applications.",
    desc: "The Nubuck collection is designed to satisfy the demands of stylish footwear, featuring a rich, innovative, and sophisticated finish. Crafted from premium European hides, it is lightly buffed to achieve a soft, velvety touch while retaining the natural grain. More colours are available, and customization is possible for various product applications."
  },
  {
    id: "f05tv-deep-red",
    title: "F05TV, Deep Red",
    fullName: "F05TV, Deep red. Aniline/full grain.",
    subtitle: "LEATHER SUITABLE FOR FOOTWEAR PRODUCTION",
    thickness: "1.2 / 1.4 mm",
    rawhide: "European",
    src: "/slides/Screenshot_8.png",
    rawMaterial: "We select the highest tier of European hides, ensuring a flawless base for ladies' luxury footwear.",
    processing: "On our premises we execute drum aniline dyeing and specialized grain conditioning to highlight a vibrant, lively red luster.",
    productDetails: "This is a fine-grain leather with beautiful aniline dye and color, giving it a lively, vibrant appearance. The leather is ideal for women’s long boots and fashionable shoes. More colours are available, and it can be modified for different uses. Its supple texture and rich finish ensure both elegance and comfort in every design.",
    desc: "This is a fine-grain leather with beautiful aniline dye and color, giving it a lively, vibrant appearance. The leather is ideal for women’s long boots and fashionable shoes. More colours are available, and it can be modified for different uses. Its supple texture and rich finish ensure both elegance and comfort in every design."
  }
];
