export const leatherGoodsProducts = [
  {
    id: "f016cmno-cream",
    title: "F016CMNO, Cream ---TYPE: Semi-Aniline/ Full Grain",
    colorName: "Cream",
    fullName: "F016CMNO, Cream---Semi-Aniline / Full Grain",
    subtitle: "LEATHER SUITABLE FOR PREMIUM LEATHER GOODS PRODUCTION",
    thickness: "1.2 / 1.4 mm",
    rawhide: "EU + GB",
    src: "/slides/f016cmno_cream.png",
    rawMaterial: "We use premium bovine skins of select European and Great Britain origin.",
    processing: "Processes carried out on our premises include fine chrome retanning and a state-of-the-art semi-aniline protective finish that yields an exceptionally smooth, rich full grain touch.",
    productDetails: "Cream is a premium bovine leather item, meticulously retanned and dyed in beautiful, pure white cream tones. Designed to satisfy high-end fashion designers, it has a robust, round-hand touch and excellent structural stability. Additional colours are available, and the retanning, dyeing, and finishing can be fully customized for different product designs.",
    desc: "This substantial round-hand leather is distinguished by its chrome retannage and technologically enhanced finish, providing a luxurious, smooth feel that satisfies customers’ demands for leather goods and footwear. More colours are available, and it can be customized for different applications."
  },
  {
    id: "f011cl-brown",
    title: "F011CL, Brown --- Aniline / Full Grain",
    colorName: "Brown",
    fullName: "F011CL, Brown---Aniline / Full Grain",
    subtitle: "LEATHER SUITABLE FOR PREMIUM LEATHER GOODS PRODUCTION",
    thickness: "1.1 – 1.2 mm",
    rawhide: "European",
    src: "/slides/f011cl_brown.png",
    rawMaterial: "We select best-in-class European rawhides known for uniform fiber density.",
    processing: "On our premises we carry out aniline drum-dyeing mixed with organic waxes and oils, enhancing the warm feel and lustrous surface.",
    productDetails: "F011CL Brown features an organic wax-mixed oil glaze with a warm feel that offers a smooth and shiny appearance. Tanned ethically, it is ideal for high-end leather goods such as luxury handbags, wallets, belts, and structural garments. Tanning and drum dyeing processes can be tailored to meet your design goals.",
    desc: "Natural-grain, wax-mixed oil dyeing with a warm feel that offers a smooth and shiny appearance. Ideal for leather goods such as luxury handbags, belts, and garments. More colours are available and can be customised for other applications."
  },
  {
    id: "f017cd-black",
    title: "F017CD, Black --- Semi-Aniline / Full Grain",
    colorName: "Black",
    fullName: "F017CD, Black---Semi-Aniline / Full Grain",
    subtitle: "LEATHER SUITABLE FOR PREMIUM LEATHER GOODS PRODUCTION",
    thickness: "1.3 – 1.5 mm",
    rawhide: "GB+EU",
    src: "/slides/f017cd_black.png",
    rawMaterial: "We use superior rawhides from Great Britain and Europe.",
    processing: "Processes performed on our premises include chromium retanning, organic drum dyeing, and protective semi-aniline top-coat glazing.",
    productDetails: "F017CD Black is a regular-grain bovine leather crafted for extreme longevity and styling flexibility. Featuring a gorgeous full grain with excellent resistance, it meets the demands of premium footwear and high-end leather goods. Tanning, retanning, and dyeing are fully customizable.",
    desc: "This is a full-grain leather characterized by chrome retannage and a semi-aniline finish with a regular grain, designed to meet the needs of customers in both the footwear and leather goods sectors. More colours are available and can be modified upon request."
  },
  {
    id: "f01ts-lavender",
    title: "F01TS, Lavender --- Semi-Aniline / Vintage",
    colorName: "Lavender",
    fullName: "F01TS, Lavender---Semi-Aniline / Vintage",
    subtitle: "LEATHER SUITABLE FOR PREMIUM LEATHER GOODS PRODUCTION",
    thickness: "0.8 – 1.0 mm",
    rawhide: "EU + Extra",
    src: "/slides/f01ts_lavender.png",
    rawMaterial: "Selected lightweight bovine hides sourced from premier farms across Europe and outer ecological zones.",
    processing: "On our premises we carry out soft retannage, careful chrome dyeing, and apply an advanced metallic lamination glaze with vintage cracking effects.",
    productDetails: "Lavender F01TS offers a striking retro-modern appeal, combining a natural crackled surface with high structural strength. Ideal for luxury purses, accessories, and artistic outerwear. Tanning and surface effects can be customized.",
    desc: "Soft, laminated cowhide with a natural crackled appearance and light thickness. Perfect for stylish leather goods such as handbags, small accessories, and garments. The leather offers a unique vintage character with a smooth touch and elegant pastel tone."
  },
  {
    id: "f010ts-light-purple",
    title: "F010TS, Light Purple --- Aniline / Full Grain",
    colorName: "Light Purple",
    fullName: "F010TS, Light Purple---Aniline / Full Grain",
    subtitle: "LEATHER SUITABLE FOR PREMIUM LEATHER GOODS PRODUCTION",
    thickness: "0.9 – 1.2 mm",
    rawhide: "European",
    src: "/slides/f010ts_light_purple.png",
    rawMaterial: "We select best-in-class European calf hides of premium origin.",
    processing: "Processes on our premises include mixed organic-vegetable and chrome retanning, full aniline dyeing, and a patent high-gloss top finish.",
    productDetails: "F010TS Light Purple has a glossy patent-glaze appearance that highlights the calfskin's natural full grain. With a solid, vibrant coloration and a soft, supple handle, it is perfect for premium outerwear and leather fashion statements. Tanning and dyeing customization are available.",
    desc: "Full-grain cow leather with a natural grain, mixed tanning, and an aniline finish featuring a glossy patent effect. It has a solid colour and a soft touch, ideal for clothing. More colours are available upon request."
  },
  {
    id: "f08ts-maroon",
    title: "F08TS, Maroon --- Nappa / Full Grain",
    colorName: "Maroon",
    fullName: "F08TS, Maroon---Nappa / Full Grain",
    subtitle: "LEATHER SUITABLE FOR PREMIUM LEATHER GOODS PRODUCTION",
    thickness: "0.9 – 1.1 mm",
    rawhide: "Italian",
    src: "/slides/f08ts_maroon.png",
    rawMaterial: "Highest quality bovine hides sourced from leading Italian tanneries.",
    processing: "On our premises we perform chrome retanning and a highly controlled drum milling process to optimize softness and elasticity.",
    productDetails: "Maroon F08TS is a classic Nappa calf article with a fine natural grain and a highly pleasant, silk-like hand feel. Extremely soft and luxurious, it satisfies the strict standards of elite fashion houses for dynamic footwear and bags. Custom color and drum-milled thickness are fully supported.",
    desc: "This Nappa leather features a smooth texture with a natural fine grain and a pleasant, soft touch. Perfect for leather goods and footwear. More colours are available upon request and offer customization"
  },
  {
    id: "f011tf-brunt-orange",
    title: "F011TF – Brunt Orange ---Semi-Aniline / Vintage",
    colorName: "Brunt Orange",
    fullName: "F011TF, Brunt Orange---Semi-Aniline / Vintage",
    subtitle: "LEATHER SUITABLE FOR PREMIUM LEATHER GOODS PRODUCTION",
    thickness: "1.2 – 1.4 mm",
    rawhide: "EU + GB",
    src: "/slides/f011tf_burnt_orange.png",
    rawMaterial: "Finest European and Great Britain rawhides.",
    processing: "We carry out chrome retanning, hot wax infusions, and an aniline pull-up finishing process that reacts dynamically to stretch.",
    productDetails: "Burnt Orange F011TF has an elegant vintage look and a silky, waxy texture with an oily pull-up effect. The leather reacts with a gorgeous lightened crackling visual when folded, perfect for rugged bags, watch straps, and historical leather goods. Tanning, retanning, and dyeing are highly customizable.",
    desc: "This article features an oily pull-up effect, a silky, waxy texture, and a subtle shine. Combining modern technology with exceptional craftsmanship, it offers a vintage appearance and a distinctive crackling sensation. This leather is recognized as an outstanding achievement in leather craftsmanship."
  },
  {
    id: "f04db-olive",
    title: "F04DB – Olive -- Semi-Aniline / Full Grain",
    colorName: "Olive",
    fullName: "F04DB, Olive---Semi-Aniline / Full Grain",
    subtitle: "LEATHER SUITABLE FOR PREMIUM LEATHER GOODS PRODUCTION",
    thickness: "1.4 – 1.6 mm",
    rawhide: "EU",
    src: "/slides/f04db_olive.png",
    rawMaterial: "We use heavy-gauge bovine hides sourced ethically from European sustainable farms.",
    processing: "Tanning operations on our premises include vegetable-chrome retanning and deep dry drum dyeing to develop a dense, round hand.",
    productDetails: "F04DB Olive is an exceptionally robust structural leather with a dry, natural touch and deep olive pigmentation. Sourced and processed ethically, it matures beautifully over time, forming a personal and valuable patina that elevates the prestige of any bag. Tanning is fully customizable.",
    desc: "This article has a dry touch and is distinguished by its round and full hand. It develops a unique and inimitable patina over time, enhancing the value and longevity of your creations. More colours are available, and customization can be provided for other applications."
  },
  {
    id: "f011tn-crimson-red",
    title: "F011TN – Crimson Red ---Semi-Aniline / Corrected Grain",
    colorName: "Crimson Red",
    fullName: "F011TN, Crimson Red---Semi-Aniline / Corrected Grain",
    subtitle: "LEATHER SUITABLE FOR PREMIUM LEATHER GOODS PRODUCTION",
    thickness: "1.2 – 1.4 mm",
    rawhide: "European",
    src: "/slides/f011tn_crimson_red.png",
    rawMaterial: "Premium bovine hides of European origin.",
    processing: "Processes include delicate grain buffing, chrome retannage, and a high-gloss two-tone tips spray finishing.",
    productDetails: "F011TN Crimson Red is a classic corrected grain cow leather that stands out with its beautiful glossy tip coating and smooth, natural handle. Its timeless two-tone finish provides depth and structural resistance, perfect for luxury goods, luggage, and shoes. Custom dyeing and retanning are available.",
    desc: "This bovine leather is distinguished by its unique and timeless corrected grain. It features a subtle two-tone effect, a glossy appearance on the tips, and a soft, natural feel. More colours are available, with customization options for other applications."
  },
  {
    id: "f06dso-orange",
    title: "F06DSO – Orange -- Semi-Aniline / Full Grain",
    colorName: "Orange",
    fullName: "F06DSO, Orange---Semi-Aniline / Full Grain",
    subtitle: "LEATHER SUITABLE FOR PREMIUM LEATHER GOODS PRODUCTION",
    thickness: "1.4 – 1.6 mm",
    rawhide: "EU",
    src: "/slides/f06dso_orange.png",
    rawMaterial: "We select best-in-class heavy European cowhides of uniform density.",
    processing: "On our premises we execute vegetable-chromium retanning, deep wash processing, and an LWG-compliant protective top glaze.",
    productDetails: "It’s even grain throughout the leather makes it suitable for the most demanding leather goods.The semi-washed effect gives each item a unique character and refinement. More colours are available, and customization is possible for other applications.",
    desc: "It’s even grain throughout the leather makes it suitable for the most demanding leather goods.The semi-washed effect gives each item a unique character and refinement. More colours are available, and customization is possible for other applications."
  }
];
